config/routes.rb
Rails.application.routes.draw do
 root 'users#index'
 resources :users
 resources :posts
 resources :comments, except: :index
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post#, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :user#, class_name: 'User', foreign_key: 'user_id'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :link, :content, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, presence: true, length: { minimum: 5, maximum: 20 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  
        def authenticate id
            @user = User.find id
            authenticate_or_request_with_http_basic do |name, password|
             authentication = (name == @user.username && password == @user.password)
            end
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:comment][:post_id])
        @comment = @post.comments.build(comment_params)
        if (@user = User.find_by username: params[:comment][:commenter])
            @comment.user_id = @user.id
        else
            @comment.user_id = 0
        end
        if @comment.save
            flash[:create] = "Comment create!"
            redirect_to @post
        else
            flash[:danger] = "Something goes wrong!"
            redirect_to @post
        end
    end
    
    private
        
        def comment_params
            params.require(:comment).permit(:commenter, :content)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action only: [:update, :destroy] do |c|
        if !params.has_key? :post
            c.authenticate params[:user_id]
        else
            c.authenticate params[:post][:user_id]
        end
    end
    
    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
    end
    
    def create
        @user = User.find(params[:post][:user_id])
        @post = @user.posts.build(post_params)
        if @post.save
            flash[:success] = "Post created"
            redirect_to @user
        else
            flash[:danger] = "Something wrong" 
            redirect_to @user
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        @user = @post.user
        if @post.update_attributes(post_params)
            flash[:success] = "Post edited!"
            redirect_to @user
        else
            flash.now[:danger] = "Something wrong with your post!" 
            render @user
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @user = @post.user
        @post.destroy
        redirect_to @user
    end
    
    private
        def post_params
            params.require(:post).permit(:link, :content)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action only: [:show, :edit, :update, :destroy] do |c|
        c.authenticate params[:id]
    end
    
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def show
        @user = User.find(params[:id])
        @post = @user.posts.build
        @posts = Post.all
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "User created!"
            redirect_to @user
        else
            flash.now[:danger] = "Something wrong"
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "User updated"
            redirect_to @user
        else
            flash.now[:danger] = "Something wrong"
            render 'edit'
        end
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_url
    end
    
    private
    
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
        

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<strong><%= comment.commenter %></strong> say:<br>
<%= comment.content %>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroReddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do | message_type, message | %>
<p><%= message_type %> -> <%= message %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_feed.html.erb
<ul><% @posts.each do |post| %>
    <li><%= link_to post.link, post_path(post, :user_id => @user.id) %></li>
<% end %></ul>

app/views/posts/edit.html.erb
<%= render 'shared/post_form' %>

app/views/posts/show.html.erb
<% link = @post.link.to_s %>
<h1><%= link_to @post.link, "http://#{link}" %></h1><br />
<%= simple_format @post.content, {class: "post" }, wrapper_tag: "div" %><br />
<h4>Share a comment:</h4><br />
<%= render 'shared/comment_form' %><br />
<hr>
<h4>Comment for this post:</h4>
<%= render @post.comments %>
<br />
<hr>
<%= link_to "back", :back %> | 
<%= link_to "edit this post",
             edit_post_path(@post) %>
<%= link_to "destroy", post_path(@post, :user_id => @post.user_id), 
            method: :delete,
            data: { confirm: "Are you sure?" } %>

app/views/shared/_comment_form.html.erb
<%= form_for @comment do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.hidden_field :post_id, :value => @post.id %>
<%= f.hidden_field :user_id, :value => params[:user_id] %>

<%= f.label :commenter %>
<%= f.text_field :commenter %>

<%= f.label :content %>
<%= f.text_area :content, placeholder: "So... what is your comment?" %>

<%= f.submit "Send comment" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <p>The form contains <%= pluralize(object.errors.count, "error") %>: </p>
    <ul><% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %></ul>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.hidden_field :user_id, :value => @post.user.id %>

<%= f.label :link %>
<%= f.text_field :link %>

<%= f.label :content %>
<%= f.text_area :content, placeholder: "So... are you thinking?" %>

<%= f.submit "Send Post" %>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.text_field :password %>

<%= f.submit "Send!" %>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>
<%= link_to 'destroy me', user_path(@user), 
                          method: :delete, 
                          data: { confirm: "Are you sure?" } %>
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<h1>Micro reddit user</h1>
<h4>Please "log-in" or create a new user</h4>
<% @users.each do |user| %><br />
    <%= link_to user.username, user %>
    <%= mail_to user.email, user.email %><br /><hr>
<% end %>
<hr>
<%= link_to "new user", new_user_path %>
    

app/views/users/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<h1>Hi <%= @user.username %>!</h1>
<ul>
    <% if @posts.empty? %>
        <h4>No post yet</h4>
    <% else %>
        <h4>Here your posts:</h4>
        <%= render 'posts/feed' %>
    <% end %>
</ul>
<h4>Create a post!</h4>
</p><%= render 'shared/post_form' %></p><br>
<%= link_to "edit my info", edit_user_path(@user) %> |
<%= link_to "new post", '#' %>|
<%= link_to "Home", root_url %>